### ISSUE TITLE
與老師討論

### ISSUE THREAD

**Issue by mitour** [cycuim-105-graduation-project/Graduation-Project#1]
與老師討論今日方向是否 OK?

**Comment by YushengLi** [comment]
麻煩 @TangBoShang 跟教授討論結束後於此 Issue 底下回報狀況，謝謝。

By the way @mitour 下次麻煩一併附上對應紀錄的連結。

**Comment by TangBoShang** [comment]
老師認為報到可以透過我們的會員註冊這方便做解決，但因討論時間過短，他可能會在禮拜五的meeting時間多加說明指導。題外話，我們可能在禮拜五討論時，另討論準備出一的命題。

**Comment by TangBoShang** [comment]
各位晚安，今天我有稍微跟老師聊了一下，老師認為我們應該繼續朝著physical web的技術前進，如果要改成寫APP可視為最下策，因為提案的技術層面可以讓我們學習新的事物，對於校內校外比賽也較能有技術層面的競賽優勢。只是會遇到的瓶頸問題，老師不介意我們把功能做得有點像是網程，因為這樣也是解決問題的一種方法，他希望我們能多Try。希望大家看過之後可以說些話，讓我知道妳們的想法! 拜託了!!
