### ISSUE TITLE
流程圖

### ISSUE THREAD

**Issue by PacyWu** [cycuim-105-graduation-project/Graduation-Project#10]
功能使用之流程圖

**Comment by mitour** [comment]
功能流程已更新於 [WIKI 功能流程](https://github.com/cycuim-105-graduation-project/Graduation-Project/wiki/%E5%8A%9F%E8%83%BD%E6%B5%81%E7%A8%8B)

**Comment by mitour** [comment]
WIKI 有更新，每一個流程都有改，主幹未更動，更詳細說明了，說明文字也未更動。
比較大的問題應該是拍照和投票基本上的流程是一樣的，還有人與人間交換電子名片的 Nearby API 運作流程部分。

**Comment by YushengLi** [comment]
@TangBoShang 麻煩幫忙確認一下現在的流程是否足以往流程圖的製作前進。

**Comment by TangBoShang** [comment]
針對使用者的流程圖沒有問題，預計今晚完成
