### ISSUE TITLE
使用情境

### ISSUE THREAD

**Issue by PacyWu** [cycuim-105-graduation-project/Graduation-Project#15]
撰寫專題的使用情境

**Comment by mitour** [comment]
[WIKI 使用情境](https://github.com/cycuim-105-graduation-project/Graduation-Project/wiki/%E4%BD%BF%E7%94%A8%E6%83%85%E5%A2%83)

**Comment by YushengLi** [comment]
@mitour 有關於寫的太隨便、太粗淺的部分我已經 Comment 在 Slack 上面，麻煩自己要求自己做事情的品質。

@PacyWu 再麻煩你督促這邊儘速完成，文件該給老師看了。

**Comment by PacyWu** [comment]
使用情境部分是我負責的，已完成唷！
若有需要修改的地方再跟我說，謝謝
