### ISSUE TITLE
專題教室網路問題

### ISSUE THREAD

**Issue by YushengLi** [cycuim-105-graduation-project/Graduation-Project#18]
@TangBoShang 專題教室電腦目前無法順利接上網際網路，學校發下來的兩個 IP 都處於不可用狀態，請確認並排解問題之後回報。

**Comment by TangBoShang** [comment]
以與助教確認兩個IP皆能使用，禮拜六早上為不知明原因突發狀態而無法連線。

**Comment by YushengLi** [comment]
Web server auto deployment settings is done.
