### ISSUE TITLE
撰寫部分初審文件

### ISSUE THREAD

**Issue by mitour** [cycuim-105-graduation-project/Graduation-Project#2]
1. 摘要
2. 專題源起
3. 專案背景
4. 專案目標
5. 預期效益
6. 專題產出
7. 未來展望

**Comment by YushengLi** [comment]
@PacyWu 因為不管是距離專題期末初審、或是創新創業競賽日期都剩下不多時間，如果有時間可以慢慢前進了，至少可以先提出有什麼東西需要補、需要大家幫忙。

至於要開共筆還是其他方式依照你的習慣即可。

**Comment by PacyWu** [comment]
今天會先把檔案整理出來唷~
