### ISSUE TITLE
借 Beacon

### ISSUE THREAD

**Issue by mitour** [cycuim-105-graduation-project/Graduation-Project#3]
盡可能找支援 Eddystone Format 及 相容於 Google Physical web 的 Device.

**Comment by YushengLi** [comment]
因為老師目前看來還沒辦法找到上一屆使用的 Beacon 設備...(印象中是 Estimote 的設備)，在那之前我們可以先來比較一下市面上支持 Eddystone 跟 Physcal Web Stadard 的設備。

Reference: [Links for list of Eddystone manufacturers](https://developers.google.com/beacons/eddystone#support_for_eddystone)

**Comment by TangBoShang** [comment]
老師已找到，目前在我這邊，一共有5顆，包含電池數十顆，因過於貴重，放前在專題教室我的電腦包裡，禮拜五前須測試並回報裝置是否正常，與電池區分有無電量。

**Comment by YushengLi** [comment]
我印象中 Beacon 好像是鈕扣電池，找個電表來測一下電池電壓，然後 Estimote Beacon 有設定用的 App，去下載來看看可不可以抓得到裝置就能知道是不是正常了。

**Comment by TangBoShang** [comment]
太好了XD 我還在在想要怎麼測試beacon，感謝萬分!只是電表測電壓我還得研究一下XD

**Comment by YushengLi** [comment]
可以找比較宅的人借借看、或是直接去五金行買一個，不過這部分其實不急，大不了先去書局買新的鈕扣電池，就可以暫時先把電池的問題排除掉。

**Comment by TangBoShang** [comment]
電池有20幾顆XD 型號是CR2450 3V 網購還是買得到的，測試同一電池結果，5個裡面有3個可以接受到major等訊號，2個故障，電池數量充足，電量測量問題暫時延後!

**Comment by YushengLi** [comment]
目前借到的裝置不良率似乎有點高，待初審結束後再儘速解決硬體裝置問題。
