### ISSUE TITLE
介面圖

### ISSUE THREAD

**Issue by PacyWu** [cycuim-105-graduation-project/Graduation-Project#9]
### 優先順序一：好友
- [x] 開啟藍芽通知
- [x] 搜尋好友
  - [x] 掃描附近裝置
  - [x] 顯示結果
- [ ] 加入好友
  - [ ] 對方同意通知
  - [x] 對方同意前可看到頁面
  - [x] 對方同意後可看到頁面(與好友頁面區分?)
- [x] 好友列表
- [ ] 好友頁面(名片、履歷?、參與場次?)
- [x] 已送出邀請列表
- [x] 已收到邀請列表
### 優先順序二：投票
- [x] 開啟藍芽通知
- [x] 搜尋投票事件
  - [x] 搜尋附近裝置
  - [x] 可投票列表
- [x] 投票
  - [x] 選項
  - [x] 完成投票畫面
  - [x] 投票結果
- [x] 昔日參與投票
  - [x] 列表
  - [x] 詳細(事件地點、事件名稱、所投選項、投票結果)
### 優先順序三：參與場次(Ticket)
- [x] 列表
- [x] 票券(QRCode)
### 次要順序
- [ ] 活動
  - [x] 列表(首頁)
  - [x] 詳細
  - [x] 報名頁面
  - [ ] 填寫報名表格
  - [x] 報名成功畫面(拿到票券)
- [ ] 推播
  - [x] Physical web
    - [x] 鎖定畫面通知
    - [x] 通知中心
    - [x] Chrome 頁面
  - [ ] 訊息
    - [ ] 鎖定畫面通知(，以 Beacon icon 取代 Chrome)
    - [ ] 通知中心
    - [x] 訊息呈現
- [ ] Settings
  - [ ] 名片
    - [x] 呈現頁面(需修改，不應同於實體名片)
    - [ ] 編輯頁面
  - [ ] 個人資料(履歷)
    - [x] 呈現頁面
    - [ ] 編輯頁面
  - [ ] 帳戶訊息
    - [ ] 呈現頁面
    - [ ] 編輯頁面
- [x] 選單
- [ ] 會員
  - [x] 登入畫面
    - [x] 一般登入
    - [x] OAuth
  - [ ] 註冊畫面
- [ ] 相片牆

**Comment by YushengLi** [comment]
@mitour 記得更新進度。

**Comment by mitour** [comment]
不定期即時更新於[ Invision](https://invis.io/697GAPPES)
